import Sidebar from "@/components/sidebar"
import Head from "next/head"
import Link from "next/link"

export default function Home() {
  return (
    <>
      <Head>
        <title>clen cat</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center items-center">
        <Sidebar />
        <div>222</div>
        <div>333</div>
      </main>
    </>
  )
}
